### ISSUE TITLE
Setup Chakra

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#1]
I am planning to build this UI library on top of [ChakraUI](https://chakra-ui.com/).

**Comment by JoelBCarter** [comment]
@Dhaiwat10 I'm not super familiar with Chakra but my question here is would it be too opinionated/limiting to take a dependency on ChakraUI?  For example if someone wanted to use Bootstrap or Tailwind while brining in our components, would that still be possible without a lot of toil?

**Comment by Dhaiwat10** [comment]
@JoelBCarter It would indeed be opinionated but here are the reasons why we chose Chakra:
1. Chakra gives you full control over the styling of the component itself. 
2. Chakra already has several handy utilities + excellent accessibility support. We cannot afford to re-invent that.

To answer your question, yes and no. You can still pass stuff like class names to our components but our components will always use Chakra under the hood.

**Comment by Dhaiwat10** [comment]
I'm closing this issue since Chakra was already setup, but feel free to keep the discussion going if you have questions or concerns. :)

**Comment by JoelBCarter** [comment]
@Dhaiwat10 I totally love the accessibility aspect of Chakra, just wondering if it would give people pause for concern in adopting this as "The Web3 UI Library" if they also had to take a hard dependency on Chakra.  I like the plan of run with it now and we can always circle back if it becomes an issue for adoption (probably won't).

**Comment by Dhaiwat10** [comment]
@JoelBCarter Your concern is completely valid! How I see it: if the library ever becomes widely-adopted, then maybe we can think of creating a headless, non-opinionated UI library. A great example  is HeadlessUI and TailwindUI.
