### ISSUE TITLE
Token amount/value input with easy conversion to-from wei<->ether

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#10]
Please take inspiration from [scaffold-eth's `EtherInput` component](https://github.com/scaffold-eth/scaffold-eth/blob/master/packages/react-app/src/components/EtherInput.jsx).

**Comment by swetshaw** [comment]
Hi @Dhaiwat10 I would like to work on this issue, I might need some help from you if that's ok? 🙂

**Comment by Dhaiwat10** [comment]
Hey @swetshaw sure thing! Really appreciate you taking initiatives on this project. :)

I think @miralsuthar also wanted to have a look at this. Maybe you two can pair program a bit and help each other out? Of course, I'm just one mention or DM away too!

**Comment by Dhaiwat10** [comment]
One thing I would suggest is waiting until I close #8. That way, you will have a clear idea of the general structure of a component. I'll make sure that I notify you two when I open a PR for that. Does that sound fair?

**Comment by swetshaw** [comment]
Hi, @Dhaiwat10 if @miralsuthar is okay doing it that way I have no issues, although I don't know how feasible it will be, can give it a try!

**Comment by Dhaiwat10** [comment]
If you prefer working by yourself, that's totally fine too. I suggested pairing up since you said you'll need help :)

**Comment by Dhaiwat10** [comment]
Hey, do you need any help? Are you blocked?

**Comment by swetshaw** [comment]
> Hey, do you need any help? Are you blocked?
Hey, I was waiting to be assigned. Thanks, @crondinini for assigning 😃. On it 🙌

**Comment by miralsuthar** [comment]
Hey, @swetshaw are you still working on this if not, then I can start working on this.

**Comment by swetshaw** [comment]
Hey @miralsuthar , I am working on this, I am facing a problem in setting up the storybook on my system.

**Comment by Dhaiwat10** [comment]
@swetshaw how can we help you, what problems are you facing?

**Comment by swetshaw** [comment]
I do not have permission to create a branch on this repo, can someone give me the access?

@Dhaiwat10 @crondinini

**Comment by Dhaiwat10** [comment]
@swetshaw you should have access now

**Comment by swetshaw** [comment]
> @swetshaw you should have access now

Thanks, I have pushed the branch

**Comment by Dhaiwat10** [comment]
@swetshaw can you create a PR and tag me there
