### ISSUE TITLE
Don't include `.dev.js` stuff in the build 

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#115]
![image](https://user-images.githubusercontent.com/39617427/145869533-7d8c04c0-c280-4dc3-9231-b0c32a8609f6.png)

https://www.runpkg.com/?@web3-ui/core@0.1.0/dist/web3-ui-core.cjs.dev.js

This shouldn't be published to npm because when `process.env.NODE_ENV` is not `production`, the `dev.js` file is being used. 

```ts
'use strict';

if (process.env.NODE_ENV === "production") {
  module.exports = require("./web3-ui-core.cjs.prod.js");
} else {
  module.exports = require("./web3-ui-core.cjs.dev.js");
}
```

**Comment by JoviDeCroock** [comment]
You can short-circuit this by changing `main` in `package.json` to `dist/web3-ui-core.cjs.prod.js` then it never enters that file

**Comment by Dhaiwat10** [comment]
@JoviDeCroock that's a great patch for now but in the long run we should aim to completely eliminate these `dev` assets from the npm bundle

**Comment by Dhaiwat10** [comment]
For now, I'm gonna use this hotfix

**Comment by JoviDeCroock** [comment]
I think `preconstruct` always does this and doesn't seem to have a way to disable that 😅

**Comment by Dhaiwat10** [comment]
@JoviDeCroock that's horrifying if true

**Comment by JoviDeCroock** [comment]
Also I think this bug is also present in production 😅 https://www.runpkg.com/?@web3-ui/hooks@0.4.0/dist/web3-ui-hooks.cjs.prod.js#238

**Comment by JoviDeCroock** [comment]
Seems to have been talked about here https://github.com/preconstruct/preconstruct/issues/92#issuecomment-527333746

**Comment by Dhaiwat10** [comment]
Wow. I need to take a breather and get back to this tomorrow. Thanks for the help along the way man, really appreciate you

**Comment by JoviDeCroock** [comment]
Got you covered mate! ❤️
