### ISSUE TITLE
ENS resolution only working on mainnet

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#120]
Right now, if we try to resolve an ENS name on any other network than mainnet we get thrown an error. This is not ideal for a user. Can we create a mainnet provider in some way so that we can resolve ENS even if on a testnet? scaffold-eth does this.

**Comment by swellander** [comment]
Hey @Dhaiwat10 - I can investigate and take a crack at this

**Comment by Dhaiwat10** [comment]
All yours @swellander

**Comment by Dhaiwat10** [comment]
@swellander any update on this one? Any blockers? How can I help? :)

**Comment by swellander** [comment]
@Dhaiwat10 thanks for checking in. Still working on this. I'll be traveling until tomorrow evening and will post a more detailed update then.

**Comment by Dhaiwat10** [comment]
@swellander awesome. Was just checking in! Take your time 😄

**Comment by Dhaiwat10** [comment]
Btw this could be useful: https://github.com/ensdomains/ui

**Comment by mathdroid** [comment]
ENS **should** only work in mainnet IMO. Should be a non-issue

**Comment by Dhaiwat10** [comment]
@mathdroid would love to hear why you think so if possible ❤️

**Comment by ankurdaharwal** [comment]
I agree with @mathdroid, ENS names only exist and should work on mainnet.

**Comment by Dhaiwat10** [comment]
> ENS names only exist and should work on mainnet
I see, but why would it be a bad idea to have them on testnets too? Is there a security or identity related issue? I'd love to learn more about the reasoning behind 'they should only work on mainnet'

**Comment by Dhaiwat10** [comment]
@swellander so we now have `useReadOnlyProvider` which accepts an RPC URL and returns a provider. We are also accepting a new prop called `rpcUrl` in our `Provider` wrapper. Maybe we can make use of that?

**Comment by swellander** [comment]
Hey @Dhaiwat10 I agree with @mathdroid and @ankurdaharwal that we shouldn't resolve mainnet ENS domains if the user is on alt networks. If a user has an ENS domain registered on the Rinkeby testnet for example, they should be able to see that name when on Rinkeby.
