### ISSUE TITLE
Remove `@emotion/core` from `components` package's dependencies

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#128]
I was trying to test out the combination of the `hooks` and `components` packages in a Codesandbox and I ran across this error after installing both of the packages. The error only appears if I also install the `hooks` package, not if I'm only using the `components` package.

![image](https://user-images.githubusercontent.com/39617427/146512295-c88fdfa6-11fe-4602-bc27-ca7a4fcdbd52.png)

[CodeSandbox link](https://codesandbox.io/s/sleepy-curran-u1rb3?file=/src/index.js)

I looked around a bit and came across this [StackOverflow comment](https://stackoverflow.com/a/65859704).

According to this comment, `@emotion/core` and `@emotion/react` are the same thing. We shouldn't have both of them in our dependencies.

**Comment by JoviDeCroock** [comment]
This was probably a dependency resolution bug, if you use this codesandbox link it should work now. `chakra-ui` needs this as a dependency so as long as we keep it in the v11 major we should be good to go on this aspect.

**Comment by Dhaiwat10** [comment]
@JoviDeCroock I understand that Chakra needs it as a dependency but it should only need _one_ of those two, shouldn't it? Sorry if I'm completely off-track and missing something

**Comment by JoviDeCroock** [comment]
Oh yeah, normally we can remove core. Mainly meant that it's working 😅
