### ISSUE TITLE
Forward refs for all components

### ISSUE THREAD

**Issue by with-heart** [Developer-DAO/web3-ui#135]
One of the requirements of any component exported from `web3-ui` (or any React component library really) should be to wrap it in a call to `forwardRef`. This would enable our users to access the `ref` for any of our components.

If you're not familiar with `forwardRef`, the beta React docs have a section explaining it: https://beta.reactjs.org/learn/manipulating-the-dom-with-refs#accessing-another-components-dom-nodes

Components to convert:

- `@web3-ui/components`
  - `Address`
  - `AddressInput`
  - `NFT`
  - `NFTCard`
  - `NFTGallery`
- `@web3-ui/core`
  - `ConnectWallet`

**Comment by OrlundoHubbard** [comment]
Hey, y'all! I'd like to take this one!

**Comment by Dhaiwat10** [comment]
Thanks @OrlundoHubbard, all yours!

**Comment by with-heart** [comment]
I created an example conversion for `NFTGallery` with some comments explaining the change: https://github.com/Developer-DAO/web3-ui/commit/dc958d6dd777548800f395abb538fbac85a33085

**Comment by Dhaiwat10** [comment]
Thanks @with-heart that's so well-made! Huge learning exp for me too

**Comment by OrlundoHubbard** [comment]
Thanks, @with-heart this was a phenomenal example!

**Comment by JorisZierold** [comment]
Hey @Dhaiwat10, while searching for a `good first issue` I came across this one. Is it still open? Or is there any other issue I could help with as newcomer?

**Comment by Dhaiwat10** [comment]
hey @JorisZierold yeah this is still open but I recommend waiting until the current refactor is done. I'll ping you here once that happens!

**Comment by e-roy** [comment]
closing because of massive structure change
