### ISSUE TITLE
Rename the core and hooks package directories

### ISSUE THREAD

**Issue by joselvelez** [Developer-DAO/web3-ui#138]
I wanted to get some feedback on the possibility of renaming the core and hooks package directories. The current names might be making it confusing as to what each actually does.

![web3-ui-current](https://user-images.githubusercontent.com/48886275/146945940-8291ec14-aa98-4dc3-aebf-a25fa842e112.png)

If I wanted to use web3-ui without any of the styling or components, I don't think I could do so with just the core package. It looks like I would need instead the hooks package, which is confusing. Should the hooks package instead be called 'core' and the core package something else? The core package seems to be more of a 'batteries included' packages that is very opinionated about how it gets implemented.

What are everyone's thoughts on this? Am I the only one struggling with this? Thank you @Dhaiwat10 for your input and taking the time to talk with me about this in the discord! :)

**Comment by with-heart** [comment]
This name scheme is somewhat unique to component libraries imo but it's fairly common to export hooks as the `/hooks` package with the "batteries included" package as `/core` (if only supporting a single framework) or `/react` (if supporting or intending to support more than one framework). I've seen that pattern followed by a number of component library-related libs like `@chakra-ui` and `@emotion`.

**Comment by Dhaiwat10** [comment]
Both of you have a valid case here! I think we can keep `core` for now but we just need some minimal documentation around what each package does so that people know which package to choose.

**Comment by joselvelez** [comment]
Sounds good. I'll close this issue and we can work on some documentation instead. Thanks!
