### ISSUE TITLE
Address component throws error when shortened=true

### ISSUE THREAD

**Issue by hone1er** [Developer-DAO/web3-ui#151]
Address component throws error when shortened=true.

<img width="1011" alt="Screen Shot 2021-12-22 at 12 07 01 PM" src="https://user-images.githubusercontent.com/24376928/147149910-8b8e2817-0e98-4e75-afc3-30eb378c85db.png">
It works correctly when i set shortened to the line below but maybe it can be solved at the component level so the dev can just set true or false without getting this error.
<img width="734" alt="Screen Shot 2021-12-22 at 12 06 40 PM" src="https://user-images.githubusercontent.com/24376928/147149881-270e0bab-da97-4c63-94ed-c58793c6cc13.png">
 So i'm assuming the Address component needs to wait for the userAddress before it tries to shorten it.

But this could also be user error on my part for not checking the connection before passing the value since the below code works as well. In which case we can close this issue
<img width="1043" alt="Screen Shot 2021-12-22 at 12 20 59 PM" src="https://user-images.githubusercontent.com/24376928/147150797-88e2a0dc-a419-4981-bcf4-a93455f5889b.png">

**Comment by Ibby-devv** [comment]
It depends where the logic fits in. The person using the Address component should ideally check whether an address exists before passing it to the Address Component. Otherwise, simply put a null check in the Address component and render an empty string if so.

**Comment by txwkx** [comment]
I'd personally vote for **not** bringing an extra dependency in the form of a hook.

Ideally, the component should be agnostic of the system's state (whenever there is a connection or not) but have validations and checks in place to secure the graceful error handling

**Comment by with-heart** [comment]
> Otherwise, simply put a null check in the Address component and render an empty string if so.

Yeah, I think this is the way to go. There's no reason an input should ever enter a state that causes the app to fail. It's the same way `<input value={undefined} />` works, where an invalid `value` like `null` or `undefined` just renders as an empty string.
