### ISSUE TITLE
UseWallet hook throws error if wallet is disconnected through metamask

### ISSUE THREAD

**Issue by hone1er** [Developer-DAO/web3-ui#153]
After connecting with the useWallet hook, if the user disconnects directly from the wallet 2 errors are thrown: "missing provider" and "unknown account #0(operation="getAddress"....)"

See video below

https://user-images.githubusercontent.com/24376928/147302858-9a6c877f-da33-4f7b-b5a0-bdb0d71ad9bd.mov

The code being used. This is a basic next-js app
<img width="1294" alt="Screen Shot 2021-12-23 at 4 52 35 PM" src="https://user-images.githubusercontent.com/24376928/147302975-7f825695-4bf5-4c67-ad22-a3ffe92e72de.png">
<img width="1294" alt="Screen Shot 2021-12-23 at 4 52 21 PM" src="https://user-images.githubusercontent.com/24376928/147302988-e82f950e-c86e-4369-9769-eee66578e5cd.png">

**Comment by Dhaiwat10** [comment]
Found out the culprit for this. Fixing
