### ISSUE TITLE
Loading status indicator / 'readiness' indicator for `useContract`

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#167]
Contracts take some time to load. Right now, if someone wrote this:

```tsx
const greeterContract = useContract(xxx,xxx);
```

Then `greeterContract` will go through the following lifecycle:

```
null          ---->           { } (empty object)        ---->            actual contract object (ready)
```

Because of that weird empty object state in the middle, just doing
```ts
if (!greeterContract)
```
doesn't work.

We need to ship an indicator that notifies the user when the contract is ready. Something like:

```tsx
const [contract, ready] = useContract(___, ___);

// ready becomes true when the contract has finished loading
```

**Comment by CatalinCsnMaster** [comment]
Hello! 😁
Can I tackle this one? 🛠

**Comment by Dhaiwat10** [comment]
@CatalinCsnMaster sure! All yours

**Comment by Dhaiwat10** [comment]
@CatalinCsnMaster hey just checking in! Do you have any blockers? How can I help?

**Comment by CatalinCsnMaster** [comment]
@Dhaiwat10 Hello! I was blocked for a second by the thought that this is too easy 😅 
Anyhow, I made a PR, please review it when you have the time and if there are any improvements that I can make, please let me know.
Also, do I need a Changeset?

**Comment by Dhaiwat10** [comment]
@CatalinCsnMaster I think you need a `patch` for the `hooks` package.

**Comment by Dhaiwat10** [comment]
Actually, I think we need a `minor` bump lol. Sorry for the confusion @CatalinCsnMaster

**Comment by CatalinCsnMaster** [comment]
I've put a minor bump in hooks package 😄
