### ISSUE TITLE
Input component with token select dropdown

### ISSUE THREAD

**Issue by Nazeeh21** [Developer-DAO/web3-ui#169]
### Description

Develop an input component that allows users to select tokens from the dropdown and specify number of tokens in the input.
User needs to pass an array of tokens required as props to add in the dropdown.

### Why is this needed?

This component will enable users to select a number of tokens using an easy configuration and without the requirement of passing the address of the token.

### Proposed Solution or API

Develop an input component accepting an array of required tokens to display in the dropdown. The selected token address by the user will be returned from the component.

eg: 
![image](https://user-images.githubusercontent.com/56908732/147381945-7e922a26-713d-4ecb-a5ec-018ae6e0a8c9.png)

**Comment by Nazeeh21** [comment]
I've been busy for the past couple of days and thus this one got delayed, sorry for that.  Finally started working on this, PR for this one will be up soon.

**Comment by with-heart** [comment]
What do we imagine the API looking like for this component? Could you write a code sample of how someone would use it?

**Comment by Nazeeh21** [comment]
@with-heart Yeah sure. I've created a gist [here](https://gist.github.com/Nazeeh21/ec736129164cf8276075b74a0563e556). I've also added some comments related to that.

Happy to hear your thoughts on this idea.

**Comment by e-roy** [comment]
closing because of massive structure change
