### ISSUE TITLE
Sign-in with Ethereum

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#17]
RoguePenguins on Discord suggested having a `Sign-in with Ethereum` button that implements a functionality similar to the one seen on https://login.xyz/.

I think this is a must-have feature.

**Comment by swellander** [comment]
Hi @Dhaiwat10 👋 mind if I take a shot at implementing this sign-in? 

Thanks for organizing this project! Seems like it has a lot of potential utility 🔧

**Comment by Dhaiwat10** [comment]
@swellander you're more than welcome to but please wait until the #3 issue gets closed! The project structure is going to change drastically

**Comment by swellander** [comment]
Sounds good, thanks for the heads up!

**Comment by RoguePenguins** [comment]
ayy so I made a buildMessage helper function for this when we're ready for it :)

**Comment by Dhaiwat10** [comment]
Thanks @RoguePenguins, will love to see it

**Comment by crondinini** [comment]
Hey @swellander, took the liberty of assigning you to this issue as I thought it was free to take because there was no one assigned.

**Comment by Dhaiwat10** [comment]
@crondinini @swellander , @RoguePenguins already put in a PR but we have put it on hold for now until we set the `@web3-ui/core` package up.
