### ISSUE TITLE
Create a readme for the core package

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#173]

**Comment by akshatamohanty** [comment]
@Dhaiwat10 happy to take this up ^ - trying to use `web3-ui/core` in a side-project, will be digging through the code anyway :)

**Comment by Dhaiwat10** [comment]
@akshatamohanty Thanks!! ❤️

**Comment by Dhaiwat10** [comment]
Feel free to use the [README for the components package](https://github.com/Developer-DAO/web3-ui/blob/main/packages/components/README.md) as a reference.

**Comment by akshatamohanty** [comment]
@Dhaiwat10 raised a PR - https://github.com/Developer-DAO/web3-ui/pull/201

btw, what's the difference between `components` and `core` - both seem to be a set of React components right now?

**Comment by Dhaiwat10** [comment]
Hey @akshatamohanty, happy new year! 

The main difference between those packages is that the `core` package is supposed to be plug-and-play & opinionated. The `components` package is supposed to just provide the general UI layout but it won't 'fetch' anything or 'do' anything for you. Basically: if you want to get started quickly -> go with core, if you want to have more control -> go with components and/or hooks. 

As more stuff gets added to the core package, this will hopefully become more clear.
