### ISSUE TITLE
Enhance `useTransaction` hook

### ISSUE THREAD

**Issue by Nazeeh21** [Developer-DAO/web3-ui#174]
Currently, we are passing the function arguments while calling the `useTransaction()` hook. 
Instead of that, we should pass the function arguments while calling the method returned from this hook. 

Refer to [this](https://twitter.com/dhaiwat10/status/1475035600877092868?s=20) tweet for more reference.

**Comment by Ibby-devv** [comment]
I can tackle this if nobody is yet assigned to it.

**Comment by Nazeeh21** [comment]
Sure.

**Comment by Ibby-devv** [comment]
I have a question regarding this hook. There doesn't appear to be a provider being used to make the contract call, is this correct?

**Comment by Dhaiwat10** [comment]
@Ibby-devv just checking in! Do you need help in any way? Any blockers?
