### ISSUE TITLE
Setup a Next.js example

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#182]
At the moment, we don't have an example app demonstrating our project. We should have one. (The `example` folder in the main branch is broken and doesn't do anything)

I tried creating a Next.js app inside the `example` folder at the root of the project using `yarn create next-app example --ts` and ended up with the usual Next.js starter template. I then did `yarn add @web3-ui/core` inside the `example` folder. This broke the app. (see SS below)
![image](https://user-images.githubusercontent.com/39617427/147489956-e51ef8df-e38e-44cc-af32-b1b7673939af.png)

Can someone help me fix this so that we can import stuff from our packages and this example add doesn't break?

**Comment by Ibby-devv** [comment]
Did you add Web3ui/core as a dependancy?
