### ISSUE TITLE
Add message signing support

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#186]
Right now our `useWallet` hook does not have any utility methods that let the devs request a signature from the user. 

This is a widely-used functionality in the ecosystem and we should have this!

**Comment by elijahhampton** [comment]
Hello 👋🏿 I would be happy to contribute and handle this issue.

**Comment by Dhaiwat10** [comment]
@elijahhampton I saw you picked up one issue already. Wanna work on that one first?

**Comment by elijahhampton** [comment]
> @elijahhampton I saw you picked up one issue already. Wanna work on that one first? You can always pick this one up later :D 

Okay that's fine

**Comment by Dhaiwat10** [comment]
Closing since our hooks have been deprecated
