### ISSUE TITLE
Add docstring for `useContract` and `useTokenBalance` hook

### ISSUE THREAD

**Issue by Nazeeh21** [Developer-DAO/web3-ui#190]
Add docstring for `useContract` and `useTokenBalance` hook. For reference, have a look at the docstring or `useTransaction` and `useWallet` hook.

**Comment by Redarcher9** [comment]
Hi @Nazeeh21, I would like to work on this issue. Can you assign this to me?

**Comment by Nazeeh21** [comment]
Sure, please go ahead

**Comment by Redarcher9** [comment]
Hi @Nazeeh21 , I've added the Docstring comments to add-DocString-useContact-useTokenBalance branch locally but not I'm not able to push the code. 
Does it have anything to do with permissions?
<img width="1025" alt="Screenshot 2022-01-06 at 4 37 04 PM" src="https://user-images.githubusercontent.com/19843336/148373799-5946a0c2-e1d9-4e54-a06a-c4bed774499f.png">

**Comment by Nazeeh21** [comment]
Yes, you can't push directly unless you have push access to the repo.

You have to fork the repo from the button on top right and then make changes to that repo and once you are done with that, then create a PR from your forked repo to this repo.

Lmk if you have any doubts or encounters any error.

**Comment by Redarcher9** [comment]
Hi @Nazeeh21 ,
Thanks for your help :)
I've raised a pull request for this issue.

**Comment by Nazeeh21** [comment]
Awesome, can you tag me over there so that I can have a look

**Comment by Redarcher9** [comment]
Sure, I've tagged you in the PR. Let me know if there's any changes are required.
