### ISSUE TITLE
Return contract function type definitions from `useContract`

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#197]
At the moment, the contract instance that the `useContract` hook returns is just a simple contract object returned from an `ethers` contract initialization. It does not contain any type definitions. We should add this.

```tsx
const [greeterContract, ready] = useContract(ADDRESS, ABI);

console.log(typeof greeterContract.greeting); // should be an async function that returns a string

console.log(typeof greeterContract.setGreeting); // should be an async function that accepts a string
```

**Comment by carlomigueldy** [comment]
I'll tackle this

**Comment by Dhaiwat10** [comment]
@allcontributors please add @carlomigueldy for code and documentation
