### ISSUE TITLE
Add ENS lookup as an option directly from Address component

### ISSUE THREAD

**Issue by hone1er** [Developer-DAO/web3-ui#200]
By default it should not do an ENS lookup but if set to `ensLookup=True` or something similar it should be able to do the lookup. 

This would be very helpful for user-interfaces that contain list of address but don't have access to `connection.ens` for each of them. Think of a etherscan like interface or an NFT collection gallery that wants to display the ENS name of the owner if they have one.

```
export default function AddressList() {
  
const addresses =
    [
    0x54eB82E4Ec25eb173E1668dd5aB0943904d87331, 
    0x25ed58c027921E14D86380eA2646E3a1B5C55A8b, 
    0xC18360217D8F7Ab5e7c516566761Ea12Ce7F9D72
    ]

let addressList = addresses.map((address, index)=>{
    return (
        <li>
        <Address value={address} ensLookup shortened copiable />
        </li>
    )})
    return (
        <ul>
       {addressList}
       </ul>
)}
```

Other options would be add a hook that would work for this purpose or make a `<AdressList />` component

Thoughts on this?

**Comment by Dhaiwat10** [comment]
I think we can start by adding that `ensLookup` prop and setting it to `true` by default. I want to set it to `true` by default because I'm assuming most people using our components will want ENS lookups but in cases like the one you mentioned, it is ideal to not do the lookup.
