### ISSUE TITLE
Add support for ERC721 and ERC1155 tokens in `TokenGate`

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#213]
At the moment the `TokenGate` (in the core package, PR coming) only works with ERC20 tokens like $USDT. Some people/DAOs like to token-gate their content via NFTs. We should let them do this. 

## Proposed API

```tsx
<TokenGate tokenContractAddress='xxxx' tokenType='ERC20' />
// tokenType -> ERC20 || ERC721 || ERC1155
```
- [x] #221
- [x] #222

**Comment by sk1122** [comment]
is anybody working on this? I wanted to work on it

**Comment by Dhaiwat10** [comment]
`TokenGate` has been deprecated. Closing this
