### ISSUE TITLE
Rename `useContract` to `useWriteContract`

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#219]
Reasons why I think we should do this:

- The `useContract` hook needs a signer in order to function. It does not even load the contract if a signer isn't there. 
- In cases where we don't need a signer (eg. when we only want to read from the contract), we now have `useReadContract`.

Would love to hear everyone's thoughts if anyone has any

**Comment by with-heart** [comment]
I think this makes sense! It adds a lot of clarity to the fact that there are differences between read/write and how they're used.

**Comment by ngnathan** [comment]
I can take this on as my first issue!
