### ISSUE TITLE
Replace uses of `null` with `undefined`

### ISSUE THREAD

**Issue by with-heart** [Developer-DAO/web3-ui#230]
> I call it my billion-dollar mistake. It was the invention of the null reference in 1965.

— [Sir Tony Hoare](https://en.wikipedia.org/wiki/Null_pointer)

JavaScript unfortunately has two billion-dollar mistakes: `null` and `undefined`.

While we can't remove them from the language, we can reduce our usage down to a single type. I'd like to propose that we replace all uses of `null` with `undefined`.

The reason I suggest `undefined` is due to its natural existence through JavaScript and TypeScript. For example, check out this TypeScript function with an optional argument:

```ts
function useOptionalArg(optionalArg?: string) {
  console.log(optionalArg)
}
```

The use of the `?` operator makes `optionalArg` have a type of `string | undefined`.

Additionally, using only `undefined` allows us to avoid awkward type situations like this one:

https://github.com/Developer-DAO/web3-ui/blob/f481a3670ec92a7653772b8ee5be3123a7641eb6/packages/hooks/src/hooks/useTokenBalance.ts#L13-L22

The type of `provider` on line 22 is `ethers.providers.Web3Provider | null | undefined`. This is due to the way `provider` is defined on `Web3Context`:

https://github.com/Developer-DAO/web3-ui/blob/f481a3670ec92a7653772b8ee5be3123a7641eb6/packages/hooks/src/Provider.tsx#L16

There's no reason for it to also be typed as `null` when it's already potentially `undefined` due to it being optional.

**Comment by Redarcher9** [comment]
Hi @with-heart ,
Can I take this up?

**Comment by etr2460** [comment]
I don't want to bikeshed too much on this issue, but I would propose we keep nulls and undefineds, but clearly specify when to use one or the other. Typically, I've used them to represent the following:

Undefined means we don't know the value of something yet. This could mean we're waiting for an API response to populate it, user input, or something else.

Null means we know the value, and that value does not exist.

An example (in psuedocode) might be the following:
```tsx
const MyApp = () => {
  // Undefined by default because we don't know what it is
  const [ensAddress, setEnsAddress] = useState<string | null>();

  useEffect(() => {
    // On the first render, look up the user's ENS address
    // This would now be either a string ("redshirt.eth") or null if the user doesn't have an ens address
    const ensAddress = getENSAddress();
    setEnsAddress(ensAddress);
  }, []);

  // Now return different UI depending on if the ENS address is undefined, null, or a string
  return (
    <div>
      {ensAddress === undefined && 'Loading ENS Address'}
      {ensAddress === null && 'You don\'t have an ENS Address yet, you should totally get one'}
      {ensAddress && `Your ENS Address is ${ensAddress}`}
    </div>
  );
}
```

What are your thoughts @with-heart @Dhaiwat10 ? Note that there's probably still value in cleaning up some places where both null or undefined are possible, but I would hesitate to create a hard and fast rule saying only use one or the other. There's value in both, and they can mean slightly different things, so I'd prefer to keep them both around in certain situations.

**Comment by with-heart** [comment]
That's interesting that you lay that case out @etr2460 because I used to hold the same view. I was pushing for essentially the same idea at my last startup I worked for and ran into a few issues:

- That concept is just not a part of the worldview of most devs, even among the more senior js devs that I worked with
- The value of trying to add that concept to everyone's worldview didn't work very well, I think mostly because it wasn't seen as very valuable
- It's not really enforceable in any way since the difference is based on intent in the mind of the author

We ended up moving everything to `undefined` and it basically didn't matter in the slightest so I came to see it as being an idea that seemed interesting and useful, but in practicality it's just not. imo there are better ways to handle the situation that makes it more obvious to the consumer than "know the distinction between `null` and `undefined`".

**Comment by dfimbres** [comment]
Can I be assigned this one.

**Comment by Dhaiwat10** [comment]
Feel free to take it @dfimbres

**Comment by e-roy** [comment]
closing because of massive structure change
