### ISSUE TITLE
The error message in NFTGallery doesn't go away when the address changes

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#246]
If there's an error in the NFTGallery component when trying to fetch the NFTs and you then change the address or re-fetch the NFTs, the error does not go away even if this time the request goes through. This is probably due to us not setting `error` to `null` when re-fetching.

https://user-images.githubusercontent.com/39617427/149676086-80ffdd2b-41d3-40b0-8ce7-db45b27e0482.mov

**Comment by CatalinCsnMaster** [comment]
Hello! Can I tackle this one?

**Comment by Dhaiwat10** [comment]
Sure @CatalinCsnMaster

**Comment by CatalinCsnMaster** [comment]
@Dhaiwat10 I made a PR, but is giving me chromatic error, about CHROMATIC_PROJECT_TOKEN, is it something that I can do?

**Comment by Dhaiwat10** [comment]
> @Dhaiwat10 I made a PR, but is giving me chromatic error, about CHROMATIC_PROJECT_TOKEN, is it something that I can do? 

There's nothing you can do about that. Chromatic does not work with forks at the moment. It's fine, don't worry
