### ISSUE TITLE
[core] Network switch component

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#247]
### Description

We should have a network switch similar to the one seen at [Uniswap](https://app.uniswap.org/#/swap) that lets people easily switch between networks. 

This network switch component should automatically send a network change request to the users' wallet when they click on an option from the dropdown.

### Why is this needed?

Different web3 apps run on different networks so it is convenient to display the current network to the user and letting them easily switch to the correct one.

### Proposed Solution or API

```tsx
import { NETWORKS, NetworkSwitch } from '@web3-ui/core';

const { mainnet, rinkeby, ropsten, polygon } = NETWORKS;

<NetworkSwitch networks=[mainnet, rinkeby, ropsten, polygon] />
```

### Additional Information

https://user-images.githubusercontent.com/39617427/149685304-76a3bf98-3920-4e54-a563-000085ed1b0c.mov

**Comment by Dhaiwat10** [comment]
Thanks @swellander

**Comment by SouravInsights** [comment]
Is anyone still working on this? @swellander & @Dhaiwat10 
Love to take this up if it's not being already implemented.

**Comment by swellander** [comment]
@SouravInsights hey, yeah working on a PR for this, should be up soon. got a little sidetracked by ethdenver!

**Comment by SouravInsights** [comment]
No worries, I'll take up something else. :-)
