### ISSUE TITLE
switchToCorrectNetwork fails if the requiredNetwork is moonriver

### ISSUE THREAD

**Issue by ImRajdeepB** [Developer-DAO/web3-ui#259]
When metamask is set to mainnet, and I want to switch to moonriver (chainId 1285), I'm getting error code 4902. This is most likely because a different [chainId/rpcUrl](https://github.com/Developer-DAO/web3-ui/blob/43d7031185f683e9e64329ba020bd721502dc513/packages/hooks/src/hooks/useWallet.ts#L58) is being added to handle the error: https://github.com/Developer-DAO/web3-ui/blob/43d7031185f683e9e64329ba020bd721502dc513/packages/hooks/src/hooks/useWallet.ts#L55

NOTE: moonriver network is already added to my metamask browser extension

**Comment by Dhaiwat10** [comment]
Thanks for pointing this out. @Nazeeh21 since you implemented this (if I'm correct), why are we switching to/ adding the chain number 61 (which is ETH Classic)?

**Comment by Nazeeh21** [comment]
Thanks for pointing this out. Instead of `0x61`, there must be the `chainId` passed by the user along with the RPC URL of that chain id. `0x61` was for testing purposes.
