### ISSUE TITLE
Switch array `args` to `arguments` on `execute` from `useTransaction`

### ISSUE THREAD

**Issue by berteotti** [Developer-DAO/web3-ui#261]
It's easier to call this function as we were calling the original function.

Current implementation:

```javascript
await execute([1,
	{
		value: ethers.utils.parseEther("0.05"),
	}
])
```

Suggested implementation:

```javascript
await execute(1,
	{
		value: ethers.utils.parseEther("0.05"),
	}
)
```

**Comment by Dhaiwat10** [comment]
Thanks, that's a great suggestion. I'll take care of this.

**Comment by berteotti** [comment]
> Thanks, that's a great suggestion. I'll take care of this.

I would like to contribute. I can do it if you don't mind 😉

**Comment by Dhaiwat10** [comment]
Oh of course, go ahead!
