### ISSUE TITLE
Monorepo setup discussion

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#27]
Please use this thread as the place to open a discussion about the monorepo setup (#26) or to suggest any improvements!

**Comment by etr2460** [comment]
oops, looks like i was a minute or two late with PR comments. I might make a PR to add in the changes i listed here: https://github.com/Developer-DAO/web3-ui/pull/26#pullrequestreview-817348782

**Comment by Dhaiwat10** [comment]
@etr2460 thank you! Please do that and I'll merge it in asap

**Comment by etr2460** [comment]
opened https://github.com/Developer-DAO/web3-ui/pull/28!

**Comment by Dhaiwat10** [comment]
#28 merged

**Comment by crondinini** [comment]
Is there any further discussion needed? Seems like the improvements are in this other issue: 
https://github.com/Developer-DAO/web3-ui/issues/33
