### ISSUE TITLE
Chain Id Formatted Incorrectly When Changing Networks

### ISSUE THREAD

**Issue by Derked** [Developer-DAO/web3-ui#273]
When changing networks/blockchains the Web3 context incorrectly updates the Chain ID from hexadecimal. For example, the localhost chain Id is stored as 1337 in decimal, but 0x539 in hex. The current formatting for 'chainChanged' just rips the 0x off the front instead of a conversion to decimal. 

Example: If you are on mainnet and switch to localhost, the chainId in the Web3 context will update to 539 instead of 1337 and there will be a mismatch between the network and chainId and correctNetwork will be false. 

In the 'accountsChanged' listener right below it, the chainId is set from the ethers provider and seems to have no issues. 

See screenshots below. I'm suggesting using the method marked by red 2 in the listener marked by the red 1. Apologies for any confusion in the explanation. 

Once I can get my environment set up properly I'd be happy to do this. Thanks :). 

![chainIdProps](https://user-images.githubusercontent.com/23644982/151639900-a791aa97-6712-4c28-8258-201a553d411a.PNG)
![web3ui issue](https://user-images.githubusercontent.com/23644982/151639905-5ea3910f-c918-4eab-bacd-36daf7936fa6.PNG)

**Comment by Derked** [comment]
@Dhaiwat10 This will be a problem on any chain where the hex conversion to decimal is not equivalent to ripping the 0x off the front. For example since Ethereum mainnet is chain ID 1 and Rinkeby is chain id 4, you won't have any issues since 1 is 0x1 in hex and 4 is 0x4 in hex. 

However, for something like Moonriver which is chain ID 1285 in decimal, the hex equivalent is 0x505. When switching to Moonriver you will get a chain ID of 505 instead of 1285. For localhost, the chain ID is 1337 in decimal or 0x539 in hex. Same problem.

**Comment by Dhaiwat10** [comment]
@Derked Ahh I see. This is a critical bug. Thanks for catching this

**Comment by Dhaiwat10** [comment]
@Derked do you want to work on this one? I can help you get your local environment all setup if needed

**Comment by Derked** [comment]
@Dhaiwat10 Yea I'm happy to do it if I can get WSL to behave. I'll connect with you to spin it up.

**Comment by shamoilarsi** [comment]
hey @Dhaiwat10 is this issue being worked on? I'd like to take a look as well. 

replacing `+newChainId.split('0x')[1];` with `+newChainId` should be a quick fix?

``` 
> const chain = "0x89"
> const formattedChain = +chain;
> formattedChain // 137
```

**Comment by Dhaiwat10** [comment]
@shamoilarsi nope, I can assign it to you if you want to work on it

**Comment by shamoilarsi** [comment]
yup I'd like to take it. how does my approach sound [here](https://github.com/Developer-DAO/web3-ui/issues/273#issuecomment-1029037443)?
