### ISSUE TITLE
Bug when switching networks (via walletconnect)

### ISSUE THREAD

**Issue by juliankrispel** [Developer-DAO/web3-ui#285]
Steps to reproduce:
1. Connect via ConnectWallet
2. Switch chain
3. Exception occurs: `Unhandled Rejection (TypeError): newChainId.split is not a function`

![image](https://user-images.githubusercontent.com/1188186/151966142-622b5c3a-e8d4-4151-8cd5-5afa73b6d221.png)

**Comment by Dhaiwat10** [comment]
I feel like this can be solved via doing `newChainId?.split` instead of `newChain.split`

**Comment by seromenho** [comment]
I think this was fixed with #297.
Maybe it can be closed, what do you think?
