### ISSUE TITLE
Connect button to prompt user to add a custom network

### ISSUE THREAD

**Issue by jwarshack** [Developer-DAO/web3-ui#290]
### Description

Just realized you are able to prompt Metamask to automatically add a custom network for the user. If a Dapp only supports a Layer 2 or Polygon for example, the user can add the network to their Metamask extension without having to add the chain id, rpc url, etc manually.

### Why is this needed?

Makes for a better UX.  

### Proposed Solution or API

Chainlist has a dashboard where you can add almost any network to your wallet. They are open sourced.  The connection code is here: https://github.com/antonnell/networklist-org/blob/main/components/chain/chain.js.

**Comment by Canopix** [comment]
I like this idea only if the user can introduce the data for itself, avoiding that some malicious app that uses this library injects a fake version of RPC of a specific Chain. 

We need to ensure that the user can verify that the data is the real data and not any fake RPC

**Comment by Dhaiwat10** [comment]
This is a great idea @jwarshack! I'll come up with a plan to implement this

**Comment by e-roy** [comment]
closing because of massive structure change
