### ISSUE TITLE
Convert to monorepo

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#3]
Manually testing the package locally using `yarn link` is painful.

Example: https://github.com/slipHQ/run-wasm

**Comment by Dhaiwat10** [comment]
Just for reference: the monorepo will contain three packages: `@web3-ui/components`, `@web3-ui/hooks` and `web3-ui`.

@crondinini feel free to keep the existing code in the `web3-ui` package and initalise 2 blank react packages for the other two. We'll migrate the code later. Let me know if I can help in any way!

**Comment by crondinini** [comment]
@Dhaiwat10 I don't think it's possible to keep the existing code in the root. One of the first things I've seen about workspaces is that we need to have a clean root and move the packages to a shared location.

**Comment by Dhaiwat10** [comment]
@crondinini Yeah that's right! What I meant was that keep the current code in the `web3-ui` package for now 🙂 Sorry, I wrote it in a confusing way
