### ISSUE TITLE
Implement cached provider in Provider component

### ISSUE THREAD

**Issue by chengsokdara** [Developer-DAO/web3-ui#310]
### Description

Currently connected state is not persisted, when I reload the page I have to connect to wallet again.

### Why is this needed?

I would like the feature to automatically connect to user wallet when user already connect it with the site once before already.

### Proposed Solution or API

when initiate web3modal we can pass cachedProvider flag

```
const web3Modal = new Web3Modal({
  ...
  cacheProvider: true,
});
```

when our page mounted we can check if there are cached provider

```
useEffect(() => {
  if (web3Modal.cachedProvider) {
    handleOnConnect();
  }
}, [])
```

### Additional Information

Example usage:
https://github.com/Web3Modal/web3modal/blob/master/example/src/App.tsx

**Comment by andriishupta** [comment]
Hello @chengsokdara 👋 

I would like to take it, if it is still valid

**Comment by jamescharlesworth** [comment]
@andriishupta are you working on this? I'd like to take it on if not.

**Comment by andriishupta** [comment]
@jamescharlesworth no, nobody answered, so I didn't start
go for it
