### ISSUE TITLE
Build error on typescript nextjs

### ISSUE THREAD

**Issue by albertputrapurnama** [Developer-DAO/web3-ui#313]
## General Description
Doing `yarn build` on nextjs project that has `web3-ui/hooks` and `ethers` doesn't work due to Typescript error. However, `yarn dev` runs fine.

I'm wondering if this is an issue with web3-ui or ethersjs.

### Steps to reproduce
1. [Create next app with typescript](https://nextjs.org/docs/basic-features/typescript#create-next-app-support)
2. Install web3-ui `yarn add @web3-ui/hooks ethers`
3. Use `useWallet` and `Provider` from `@web3-ui/hooks`
4. `yarn build`

You should see error like the following:
![Screenshot from 2022-03-02 22-22-59](https://user-images.githubusercontent.com/14824254/156508332-5d12e4d9-f93f-41d5-9f85-437d5bfcbf59.png)

### Reproducible repo
https://github.com/albertputrapurnama/web3-ui-next-ts-example

To reproduce in this repository:
1. Clone the repo
2. `cd` into it
3. `yarn`
4. `yarn build`

You should try `yarn dev` too and see if it works on your end.

**Comment by albertputrapurnama** [comment]
I'm kindof answering my own question here, but I found the issue from https://github.com/ethers-io/ethers.js/issues/1540#issuecomment-854857525

Turns out we're importing the .ts file directly from `@ethersproject/providers/src.ts/json-rpc-provider`  can be seen on these files:
- packages/components/src/components/AddressInput/AddressInput.tsx
- packages/hooks/src/Provider.tsx

These imports causes ts projects that have "strict" mode set to `true` to have compile error.

I have a fix already on going, but still waiting for the team to add me to the org.

I have added my github username in github-org-invitations channel on Dev Guild.

**Comment by ernestognw** [comment]
Hey sir, I opened a PR that fixes the type checking, but it still fails as the `web3-ui` package exposes `.ts` files and not transpiled `.js` files.

You'll probably need to add extra configuration after the PR is merged, this is the workaround I did, hopefully it helps you as well:

```
// next.config.js
module.exports = () => {
  /** @type {import('next').NextConfig} */
  const nextConfig = {
    reactStrictMode: true,
    // Ugly ts workaround as per https://github.com/vercel/next.js/issues/5666
    webpack: (config) => {
      config.module.rules.forEach((rule) => {
        if (rule.test) {
          const ruleContainsTs = rule.test.toString().includes("ts|tsx");

          if (
            ruleContainsTs &&
            rule.use &&
            rule.use.loader === "next-babel-loader"
          ) {
            rule.include = undefined;
          }
        }
      });

      return config;
    },
  };

  return nextConfig;
};
```

**Comment by albertputrapurnama** [comment]
Awesome @ernestognw, thank you!
