### ISSUE TITLE
it seems no export for NetworkSwitch component

### ISSUE THREAD

**Issue by xdlrt** [Developer-DAO/web3-ui#326]
https://github.com/Developer-DAO/web3-ui/blob/ef8df06dea5b36c4f5d65bf6e37288eaa9571146/packages/core/src/components/index.ts#L2

it seems no export for NetworkSwitch component, maybe this is a careless problem.

**Comment by seromenho** [comment]
Can I take this one? Anyone working on it?

**Comment by xdlrt** [comment]
thanks bro😁
