### ISSUE TITLE
Clean up workspaces

### ISSUE THREAD

**Issue by with-heart** [Developer-DAO/web3-ui#33]
As we're transitioning to a monorepo setup with `packages/components` and `packages/hooks`, we're ending up in a situation where we have unnecessary duplication of scripts, configs, and files. 

The goal of this issue is to collect all of these in one place so we can resolve them after the bulk of monorepo setup is complete.

- [x] Merge package-specific Storybook configs into a single root config for all packages (#32)
- [x] #141
- [x] #142
- [x] Extend package-specific `tsconfig.json`, `jest.config.js`, etc. from root config files
- [x] Use a single root `.prettierrc` and remove package-specific configs
  - [ ] Move to slightly more standard `prettier` settings

**Comment by crondinini** [comment]
@with-heart Could you elaborate on what more standard prettier settings would be?
