### ISSUE TITLE
Hooks discussion

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#36]
Let's use this issue as a place to discuss hooks. This is what I'm thinking of as the initial hooks:

1. [`useWallet`](https://github.com/Developer-DAO/web3-ui/blob/master/packages/hooks/src/hooks/useWallet.ts)
Contains information about the wallet connection and has helper methods like `connectWallet`, `disconnectWallet`.
____

- [ ] useContract

I can't think of more hooks at the moment. Please feel free to open a discussion and share ideas!

**Comment by Nazeeh21** [comment]
Thanks @Dhaiwat10, for listing all the hooks along with the details

**Comment by christiananese** [comment]
Couldn't we use [TypeChain](https://github.com/dethcrypto/TypeChain) to generate the type definitions?

**Comment by crondinini** [comment]
Closing this in favor of https://github.com/Developer-DAO/web3-ui/issues/37
