### ISSUE TITLE
Dropdown Element

### ISSUE THREAD

**Issue by e-roy** [Developer-DAO/web3-ui#379]
Currently we have a [DropdownMenu element](https://github.com/Developer-DAO/web3-ui/tree/main/packages/components/src/elements/DropdownMenu)

This should be renamed to Dropdown

A lot will be removed from this element to get to the goal of a single <Dropdown /> element

The element should act similar to this [tailwind dropdown component](https://tailwindui.com/components/application-ui/elements/dropdowns)

props will include:
- label?: string
- placeholder?: string
- items: string[]
- onSelect?: (val: any) => void

**Comment by Nazeeh21** [comment]
Can I work on this issue?

**Comment by e-roy** [comment]
@Nazeeh21 you got it! :)  

let me know if you have any issues or questions

**Comment by Nazeeh21** [comment]
Sure thing
