### ISSUE TITLE
ENS Avatar component

### ISSUE THREAD

**Issue by e-roy** [Developer-DAO/web3-ui#383]
### Description

A simple web3 avatar component

### Why is this needed?

need a web3 avatar component

### Proposed Solution or API

4 working files:

- ENSAvatar.tsx
- ENSAvatar.test.tsx
- ENSAvatar.stories.tsx
- index.ts

[wagmi hook to use](https://wagmi.sh/docs/hooks/useEnsAvatar)

build using the  [Avatar element](https://github.com/Developer-DAO/web3-ui/tree/main/packages/components/src/elements/Avatar)

component props :

`ENSAvatar = { address: string, size?: string, shape?: string }`

use [jazzicon](https://www.npmjs.com/package/@metamask/jazzicon) as a fallback

**Comment by remiroyc** [comment]
Hey @e-roy I'll be happy to take care of it as my first contribution if you want
