### ISSUE TITLE
Token Balance Component

### ISSUE THREAD

**Issue by AlexNi245** [Developer-DAO/web3-ui#42]
Hi, I'm thinking to build a component, that is displaying the user balance of a certain token. 
Personally, I like the approach dotmerketcap.com goes design-wise.

So I think the component would have the following params

- Contract Address (the address where the token's contract is deployed)
- Img (Path to Logo)
- Value in USD (the ability to pass the current price of the token per USD )

If the user is connected with his wallet then the balance of the certain token will be fetched. Otherwise, I think we can show them either an empty state or just the balance of 0.

<img width="977" alt="Screenshot 2021-11-30 at 23 06 50" src="https://user-images.githubusercontent.com/26583503/144136930-0921e72a-4d9b-4bbf-81b4-60472e8608b9.png">

**Comment by etr2460** [comment]
I love this idea, and would love to see you build it!

a couple thoughts (possibly feasible). i wonder if:
- there's a way to fetch the image for the logo from somewhere else and not require the user to provide it? is there a centralized/decentralized source/api for ERC-20 tokens?
- we should add a default integration with a coinmarketcap (or other) api and let the user pass in an api key to then render the value in USD (without needing to pass it in)
- we should structure this with a subset of commonly used tokens supported by default (and include the img/svg in the ui package), but then have a fallback for unrecognized contract addresses

**Comment by Dhaiwat10** [comment]
Great idea @AlexNi245. If you want to work on this, I can move this to the checklist (#7)

**Comment by AlexNi245** [comment]
thank you for replying @etr2460 @Dhaiwat10 I will build a component later on and figure out how we can do the thing @etr2460 suggested. 

Yes would be nice if you can move it to the checklist and assign me :)

**Comment by Dhaiwat10** [comment]
There you go @AlexNi245

**Comment by Ibby-devv** [comment]
@AlexNi245 Here's the URL you'll need to fetch a token's logo.

https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/[tokenContractAddress]/logo.png

Ensure the address is in the Checksum format. EthersJs has a utility for this. See below.

// Injects the checksum (via upper-casing specific letters)
getAddress("0x8ba1f109551bd432803012645ac136ddd64dba72");
// '0x8ba1f109551bD432803012645Ac136ddd64DBA72'

**Comment by AlexNi245** [comment]
Thank you for sharing this @Ibby-devv I'll try to get something working during the weekend!

**Comment by Dhaiwat10** [comment]
@AlexNi245 are you planning on working on this component since the hook has now been added?

**Comment by AlexNi245** [comment]
@Dhaiwat10 yes for sure. I actually needed the hook to make this component more useful :)
