### ISSUE TITLE
Setup Storybook deployments (and preview deployments)

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#49]
It would be great to have a deployed version of our Storybook(s) that anyone can access without having to pull down a branch and starting the Storybook server locally. This will be helpful for reviewing PRs too.

Helpful links:
- https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/
- https://www.chromatic.com/

**Comment by etr2460** [comment]
I was thinking about setting this up with vercel originally, but chromatic would probably work too. love the idea!

**Comment by with-heart** [comment]
@alanpcurrie has done a lot of work in a similar direction with https://github.com/Developer-DAO/developerdao.com/pull/178. Might be interesting to take a look at his work or have him assist with this as well!

**Comment by christiananese** [comment]
Hey @etr2460 are you already working on this one? If not  @Dhaiwat10 can I be assigned?

**Comment by Dhaiwat10** [comment]
Assigning you @christiananese, grazie

**Comment by etr2460** [comment]
yup, i haven't dug into it, it's all yours @christiananese !

**Comment by etr2460** [comment]
fyi https://github.com/Developer-DAO/web3-ui/pull/60 alters the storybook setup somewhat (puts both hooks and components into the same storybook) so you might need to rebase on it before PRing any work here. let me know if you need help!

**Comment by christiananese** [comment]
Closing this [PR #80](https://github.com/Developer-DAO/web3-ui/pull/80)
