### ISSUE TITLE
List of components

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#5]
This is what I'm thinking of for the initial set of components we want to develop:

- Address (w/ ens integration)
- AddressInput
- EtherInput
- Web3Modal connection (global context passed down from web3-ui's `<Provider />`)
- Switch to correct network
- Transaction updates (wait, success, failure)

Most of these are inspired from scaffold-eth. Feedback and suggestions welcome!

**Comment by Ibby-devv** [comment]
Connect Wallet Button

**Comment by swetshaw** [comment]
A Component for displaying the NFTs (customized accordingly):
- Art
- Music
- Video, etc

**Comment by Canopix** [comment]
A mechanism to request "Change" to the correct Network if is needed. 
Like, the dApps need to be connected to BSC and the user is in Ethereum. Request the change

**Comment by etr2460** [comment]
[Token Balance component](https://github.com/Developer-DAO/web3-ui/issues/42) (thanks @AlexNi245)

**Comment by crondinini** [comment]
Closing this in favor of #7.
