### ISSUE TITLE
`<Avatar />`

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#66]
### Description

An Avatar component that renders the avatar NFT linked with an ENS would be handy. 

https://defireport.io/nft/ens-now-supports-nft-avatars-for-your-profile/

### Why is this needed?

Quite a few people are using their ENS as their online identity now which includes linking one of their NFTs to their ENS as their avatar. It would be great if developers had an handy component that renders this avatar.

### Proposed Solution or API

```tsx
<Avatar address='dhaiwat.eth' />

// or

<Avatar address='0x0ED6Cec17F860fb54E21D154b49DAEFd9Ca04106' />
```

**Comment by sherodtaylor** [comment]
@Dhaiwat10 shouldn't this resolve address instead of ens because most likely you will have the address from connecting your wallet.m

**Comment by Dhaiwat10** [comment]
@sherodtaylor I see your point. Changing it now

**Comment by sherodtaylor** [comment]
@Dhaiwat10 np or you can accept both do both a reverse + normal lookup and just call the field address as long as you document both can be used but most of the use case would be a reverse lookup tbh.

**Comment by jwarshack** [comment]
is this closed?

**Comment by Dhaiwat10** [comment]
@jwarshack nope. Still up for taking

**Comment by christiananese** [comment]
@Dhaiwat10  Someone already working on it?  If not I would assign myself.

**Comment by jwarshack** [comment]
@christiananese @Dhaiwat10 I was going to take it on tomorrow, but you're welcome to give it a go if you'd like

**Comment by christiananese** [comment]
@jwarshack all yours :rocket:

**Comment by rekpero** [comment]
Hey @Dhaiwat10 @jwarshack anyone taking this up, if not, I would like to contribute to this issue.
I have worked on ENS for my projects, might as well give this a try.

**Comment by jwarshack** [comment]
Hey @rekpero! I am working on this right now.
