### ISSUE TITLE
Custom Web3Modal providers

### ISSUE THREAD

**Issue by Nazeeh21** [Developer-DAO/web3-ui#75]
In the **useWallet** hook, currently, we are providing support for Metamask and WalletConnect providers.
I have created PR #68 to add support for more providers.

This issue is created to discuss whether to provide support to pass any (custom) Web3Modal providers the user pleases. This is the continuation of the discussion from PR #68.

**Comment by Dhaiwat10** [comment]
This is the API I was thinking of for the `<Provider />` component in the `hooks` package:

```tsx
<Provider network='xyz' walletProviders=[{ package: WalletConnectProvider, etc....  }] />
```

**Comment by Dhaiwat10** [comment]
`walletProviders` being an optional prop, of course

**Comment by Dhaiwat10** [comment]
@Nazeeh21 are you planning to address this issue in #68? If yes, please rename that PR and tag me when it's ready for review

**Comment by Nazeeh21** [comment]
Yes, I'm planning to address this in #68. I'll rename that and tag you once it's ready for review.
