### ISSUE TITLE
Replace divisive language `master` to `main`

### ISSUE THREAD

**Issue by maximebonhomme** [Developer-DAO/web3-ui#77]
gm frens 👋 

### Why
We should move away from divisive/offensive language as much as we can. As a diverse and inclusive commuity it's our job to make sure everyone feels safe and welcome.

You can read more on [this statement](https://sfconservancy.org/news/2020/jun/23/gitbranchname/).

### How
Changing the default branch from `master` to `main` is very easy and can be done inside [the repo settings](https://github.com/github/renaming) and any admin should be able to do this.

If for some reason we can't do it from the settings, we could do [it manually](https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/).

Happy to help if needed!

**Comment by etr2460** [comment]
@Dhaiwat10 I think you should be an admin here. Could we make this change?

**Comment by maximebonhomme** [comment]
I assume it automatically updates all PRs with `main` as destination but let's double check when making the change

**Comment by Dhaiwat10** [comment]
@maximebonhomme thanks for bringing this up. The template we were using unfortunately was quite old and was still using `master`. Renamed to `main` just now!
