### ISSUE TITLE
Update Address component to display shortened address

### ISSUE THREAD

**Issue by maximebonhomme** [Developer-DAO/web3-ui#86]
### Description

Would be handy to be able to display a shortened version of the address as well as having a one click copy to clipboard functionality on it.

### Why is this needed?

Wallet addresses are far too long and in most cases we don't need to display it in full in our dapp.

Showing the first 4 and last 4 chars is usually enough to get a glimpse of which address we're using.

We usually do things with an address, like copy and paste it into etherscan to check some transactions, paste it into opensea to see the account's NFTs etc... Since we're only showing the first/last 4 chars we need a way to copy to clipboard easily.

### Proposed Solution or API

This ticket includes 2 changes really:
- New prop on `Address` called `shortened` (bool) to display 4 first/last chars of an address
- Copy full address to clipboard onClick

Good to haves would be:
- Visual hint to show that the full address can be copied
- Visual feedback when address has been successfully copied to clipboard

### Additional Information

Let's start with the basic requirements and can work on the good to haves if we have time.

Make sure to create a new ticket with good to haves (as I think they are valuable) if we can't do this as part of this issue for some reason.

**Comment by maximebonhomme** [comment]
Can anyone assign this to me @Dhaiwat10 ? Will aim to finish this by the 13th

**Comment by Dhaiwat10** [comment]
Done @maximebonhomme, thanks for taking the initiative on this one!

**Comment by joselvelez** [comment]
I just noticed this issue before submitting PR #91 with some of this functionality. Should I cancel my PR?

**Comment by Dhaiwat10** [comment]
@joselvelez no keep it for now. Let's wait until @maximebonhomme turns in their PR

**Comment by maximebonhomme** [comment]
amazing @joselvelez just saw your PR. I haven't started working on this yet but feel free to work on this if you want, otherwise I'll make a start on this tomorrow :)

**Comment by joselvelez** [comment]
I just added #95 to add the shorten functionality. It does not have the copy address functionality yet. I'm doing small bits to get a hang of making contributions. Let me know if you want to do the copy address piece.

**Comment by maximebonhomme** [comment]
amazing thanks @joselvelez! Let's get that PR reviewed and merged and I'll work on the copy address functionality today 👍
