### ISSUE TITLE
The README is not being published to npm

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/web3-ui#87]
https://www.npmjs.com/package/@web3-ui/components
https://www.npmjs.com/package/@web3-ui/hooks

I published the `components` and `hooks` packages to npm using `yarn build` and `npm publish`. The README did not go through.

**Comment by christiananese** [comment]
I think that's the default behaviour.
As I'm aware of `npm publish` looks in the root of the package that's beeing published.

So for the hooks package, it looks for a `README` file inside the hooks folder, same for the components.

**Comment by Dhaiwat10** [comment]
@christiananese that makes sense. But the plan (for now) was to have a common LICENSE and README file. Is it possible for us to pull these two files from the root when building the individual packages?
