### ISSUE TITLE
TokenGate component

### ISSUE THREAD

**Issue by hone1er** [Developer-DAO/web3-ui#98]
### Description

I want to create a component that restricts access to all child components unless certain erc-20/erc-721 token requirements are met. It would take in a contract address and required number of tokens(defaults to 1) as props to determine access.

### Why is this needed?

I think adding this component would make it easier to restrict access to a small part or whole sections of UI based on different tokens or amounts of tokens in a users wallet. For example some UI elements might be unlocked at 1 token while others may require 10 tokens to gain access. Further parts of the UI could be locked by a completely different token. This wrapper component will make implementing something like that quick and easy.

### Proposed Solution or API

https://gist.github.com/hone1er/bff36ccb8b23f7c24fa9f93389272e3f

@Dhaiwat10 check it out

**Comment by Dhaiwat10** [comment]
@hone1er this will be extremely useful. We can even make a wrapper around this in the `core` package which will work flawlessly. Let's create this with the API you proposed in the `components` package for now!

**Comment by Dhaiwat10** [comment]
Should I assign you?

**Comment by hone1er** [comment]
> Should I assign you?

Yes please, i would love to work on this
